config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:create, :new, :destroy]

  resources :questions
  resources :answers, only: [:destroy, :edit, :update, :create]

  resources :tags, only: [:destroy, :edit, :update, :create, :index, :show] do
    resource :favorite, only: [:create, :destroy]
  end
  resources :taggables, only: [:create, :destroy]
  resource :favorite, only: [:show]

  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :votes, only: [:create]
  delete "votes", to: "votes#destroy"
  post "vote", to: "votes#upvote"
  delete "vote", to: "votes#downvote"

# Backbone App
  namespace :api do
    resource :session, only: [:create, :destroy] do
      get "current", to: "sessions#current"
    end
    get "notifications/:id", to: "notifications#read"
    get "notifications", to: "notifications#index"
    get "users/search/", to: "users#search"
    resources :users, only: [:create, :destroy, :index, :show, :update]
    get "questions/unanswered", to: "questions#unanswered"
    get "questions/noanswers", to: "questions#no_answers"
    resources :questions, only: [:create, :show, :index, :update, :destroy]
    post "questions/:id/best", to: "questions#best_answer"
    resources :answers, only: [:create, :destroy, :update, :show]
    resources :comments, only: [:create, :destroy, :update]

    post "tags/search/", to: "tags#search_chat"
    get "tags/search/", to: "tags#search"
    resources :tags, only: [:destroy, :edit, :update, :create, :index, :show] do
      resource :favorite, only: [:create, :destroy]
    end
    resources :taggables, only: [:create]
    delete "taggables", to: "taggables#destroy"
    get "favorites", to: "favorites#show"
    post "vote", to: "votes#upvote"
    delete "vote", to: "votes#downvote"
    post "chats/", to: "chats#set_main_chat"
    post "chats/:name/", to: "chats#set_chat_channel"
    get "chats/:name/", to: "chats#get_history"
    post "search/", to: "searches#search"
  end

# Switch between rails and backbone here
  root to: "apps#index"
# root to: "questions#index"
end

app/models/question.rb
class Question < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:title, :body]
  paginates_per 10

  validates :user, :title, :body, presence: true
  validates :title, uniqueness: true

  belongs_to :user, inverse_of: :questions
  has_many :answers, inverse_of: :question, dependent: :destroy
  has_many :taggables, as: :taggings
  has_many :tags, through: :taggables, source: :tag
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  scope :unanswered, -> {
    where("id NOT IN (
      SELECT DISTINCT question_id
      FROM answers
      WHERE answers.is_best = true
    )")
  }
  scope :no_answers, -> {
    where("id NOT IN (
      SELECT DISTINCT question_id
      FROM answers
    )")
  }

  def vote_count
    if self.meta_vote_count
      self.votes.sum(:vote_type) + self.meta_vote_count
    else
      self.votes.sum(:vote_type)
    end
  end

  def best_answer
    @best_answer = self.answers.where(is_best: true)
    @best_answer.count == 0 ? nil : @best_answer.first
  end

  def best_answer=(answer)
    return nil unless self.answers.include?(answer) &&
      self.answers.where(is_best: true).count == 0
    answer.is_best = true
    answer.save
  end

  def best_answer?
    self.answers.where(is_best: true).count > 0
  end

end

app/controllers/api/questions_controller.rb
class Api::QuestionsController < Api::ApplicationController
  before_action :require_login, only: [:create, :update, :destroy]

  def index
    # @questions = Question.all
    sort = params[:sort] || 'id asc'
    filter = Time.now - 1.month if params[:filter] === "month"
    filter = Time.now - 1.year if params[:filter] === "year"

    @questions = filter ? Question.where("meta_create_date > ? ", filter ) : Question.all
    current_page = params[:page] || 1
    @questions = @questions.order(sort).page(current_page)
    @total_pages = @questions.total_pages
    render template: "api/questions"
  end

  def show
    @question = Question.includes(:user,
    :tags,
    :comments,
    answers: :user,
    comments: :user,
    answers: :comments,
    answers: { comments: :user }).find(params[:id])
    render template: "api/question"
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
        render template: "api/question"
    else
      render json: "{ 'error': 'Cannot Create question #{@question.errors.full_messages}'}",
        status: :unprocessable_entity
    end
  end

  def update
    @question = Question.find(params[:id])
    if not_owner?(@question)
      render json: "{ 'error': 'not your question!'}",
        status: :unprocessable_entity
    elsif
      @question.update(question_params)
      render template: "api/question"
    else
      render json: "{ 'error': '#{@question.errors.full_messages}'}",
        status: :unprocessable_entity
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if not_owner?(@question)
      render json: "{ 'error': 'not your question!'}",
        status: :unprocessable_entity
    elsif @question.destroy
      render template: "api/question"
    else
      render json: "{ 'error': '#{@question.errors.full_messages}'}",
        status: :unprocessable_entity
    end
  end

  def unanswered
    # @questions = Question.all
    current_page = params[:page] || 1
    @questions = Question.unanswered.page(current_page)
    @total_pages = @questions.total_pages
    render template: "api/questions"
  end


  def no_answers
    # @questions = Question.all
    current_page = params[:page] || 1
    @questions = Question.no_answers.page(current_page)
    @total_pages = @questions.total_pages
    render template: "api/questions"
  end

  def best_answer
    @question = Question.find(params[:id])
    @answer = Answer.find(params[:answer_id])
    if !@question || !@answer
      render json: "{ 'error': 'not a valid question or answer!'}",
        status: :unprocessable_entity
    elsif not_owner?(@question)
      render json: "{ 'error': 'not your question!'}",
        status: :unprocessable_entity
    elsif @question.best_answer?
      render json: "{ 'error': 'aleady has best answer!'}",
        status: :unprocessable_entity
    elsif @question.best_answer = @answer
      render json: { msg: 'updated!'}.to_json
    else
      render json: "{ 'error': 'cannot update best answer!'}",
        status: :unprocessable_entity
    end
  end


  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_login, only: [:create, :new, :edit, :update, :destroy]

  def index
    @questions = Question.all
    render :index
  end

  def show
    @question = Question.includes(:user,
    :tags,
    :comments,
    answers: :user,
    comments: :user,
    answers: :comments,
    answers: { comments: :user }).find(params[:id])
    render :show
  end

  def new
    @question = Question.new
    render :new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to question_url(@question)
    else
      flash[:msg] = @question.errors.full_messages
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
    if check_owner(@question)
    else
      render :edit
    end
  end

  def update
    @question = Question.find(params[:id])
    if check_owner(@question)
    elsif
      @question.update(question_params)
      redirect_to question_url(@question)
    else
      flash[:msg] = @question.errors_full_messages
      redirect_to question_url(@question)
    end
  end

  def destroy
    @quesiton = Question.find(params[:id])
    if check_owner(@question)
    elsif
      @quesiton.destroy
      redirect_to questions_url
    else
      flash[:msg] = @question.errors_full_messages
      redirect_to question_url(@question)
    end
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<% button_text = question.persisted? ? "Update Question" : "Ask Question"  %>
<% action = question.persisted? ? question_url(question) : questions_url   %>
<% method = question.persisted? ?  "PATCH" : "POST" %>
<form action="<%= action %>" method="post">
  <%= autho_token %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label for="title">title</label>
  <input type="text" id="title" name="question[title]" value="<%= question.title %>">
  <label for="question"></label>
  <textarea id="question" name="question[body]"><%= question.body %></textarea>
  <input type="submit" name="submit" value="<%= button_text %>">
</form>

app/views/questions/edit.html.erb
<h1>Edit Your Question</h1>
<%= render "form", question: @question %>

app/views/questions/index.html.erb
<h1>All Question</h1>
<ul>
<% @questions.each do |question| %>
  <li><a href="<%= question_url(question) %>"><%=h question.title %></a></li>
  <% if is_logged_in? && current_user == question.user %>
    <form action="<%= question_url(question) %>" method="post">
      <%= autho_token %>
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="delete question">
    </form>
  <% end %>
<% end %>

</ul>

<% if is_logged_in? %>
<a href= "<%= new_question_url %>"> Ask A Question!</a>
<% end %>

app/views/questions/new.html.erb
<h1>Ask A Question</h1>
<%= render "form", question: @question %>

app/views/questions/show.html.erb
<h1>Question: <%=h @question.title %></h1>
<p>
  <% puts @question.votes %>
  <% @question.votes.each do |vote|  %>
  <% puts vote.vote_type %>
  <% end %>
  <strong>votes: <%= @question.votes.sum(:vote_type) %></strong>
  <%=h @question.body %>
  <% if is_logged_in? %>
    <form action="<%= vote_url %>" method="post">
      <%= autho_token %>
      <input type="hidden" name="vote[id]" value="<%= @question.id %>">
      <input type="hidden" name="vote[type]" value="Question">
      <input type="submit" value="upvote!">
    </form>
    <form action="<%= vote_url %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <%= autho_token %>
      <input type="hidden" name="vote[id]" value="<%= @question.id %>">
      <input type="hidden" name="vote[type]" value="Question">
      <input type="submit" value="down vote!">
    </form>
  <% end %>
</p>
  <% if @question.comments.length > 0 %>
    <strong>comments: </strong>
  <% end %>
  <% @question.comments.each do |comment| %>
    <p>
      <%= comment.body %>
      <span>by <%= comment.user.username %></span>

      <% if is_logged_in? && current_user == @question.user%>
        <a href="<%= edit_comment_url(comment) %>">edit comment</a>
        <form action="<%= comment_url(comment) %>" method="post">
          <%= autho_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="delete comment">
        </form>
      <% end %>
      <% if is_logged_in? %>
        <%= render "comments/form", object: comment %>
      <% end %>
    </p>
  <% end %>
  <% if is_logged_in? %>
    <%= render "comments/form", object: @question %>
  <% end %>
<p>
  by: <a href="<%= user_url(@question.user) %>"><%=h @question.user.username %></a>
</p>
<p>
  <span>Tags:</span>
  <br>
  <% @question.tags.each do |tag| %>
    <a href="<%= tag_url(tag) %>"><%= tag.name %></a>
    <% if is_logged_in? %>
      <form action="<%= tag_url(tag) %>" method="post">
        <%= autho_token %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="untag">
      </form>
    <% end %>
  <% end %>
</p>
<% if is_logged_in? %>
  <form action="<%= taggables_url %>" method="post">
    <%= autho_token %>
    <input type="hidden" name="_method" value="post">
    <label for="tag">Add Tag To Question: </label>
    <input type="text" name="taggable[name]">
    <input type="hidden" name="taggable[taggingstype]" value="Question">
    <input type="hidden" name="taggable[taggingsid]" value="<%= @question.id %>">
    <input type="submit" value="tag it!">
  </form>
<% end %>
<% @question.answers.each do |answer| %>
  <p>
    Answer:
    <strong>votes: <%= answer.votes.count %></strong>
    <%= answer.body %>
    <% if is_logged_in? %>
      <form action="<%= votes_url %>" method="post">
        <%= autho_token %>
        <input type="hidden" name="vote[id]" value="<%= answer.id %>">
        <input type="hidden" name="vote[type]" value="Answer">
        <input type="submit" value="upvote!">
      </form>
      <form action="<%= votes_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <%= autho_token %>
        <input type="hidden" name="vote[id]" value="<%= answer.id %>">
        <input type="hidden" name="vote[type]" value="Question">
        <input type="submit" value="down vote!">
      </form>
    <% end %>
    <%= render "comments/form", object: answer %>
    <% if answer.comments.length > 0 %>
      <strong>comments: </strong>
    <% end %>
    <% answer.comments.each do |comment| %>
      <p>
        <%= comment.body %>
        <span>by <%= comment.user.username %></span>
        <% if is_logged_in? && current_user = comment.user %>
          <a href="<%= edit_comment_url(comment) %>">edit comment</a>
          <form action="<%= comment_url(comment) %>" method="post">
            <%= autho_token %>
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="delete comment">
          </form>
        <% end %>
      </p>
      <%= render "comments/form", object: comment %>
    <% end %>

    <span>by <a href="<%= user_url(answer.user) %>"><%=h answer.user.username %></a></span>
    <% if is_logged_in? && current_user == answer.user %>
      <a href="<%= edit_answer_url(answer) %>"> Edit Answer</a>
      <form action="<%= answer_url(answer) %>" method="post">
        <%= autho_token %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="delete answer">
      </form>
    <% end %>
  </p>
<% end %>
<% if is_logged_in? && current_user == @question.user %>
  <a href="<%= edit_question_url(@question) %>">edit question</a>
<% end %>

<a href="<%= questions_url %>">see all question</a>
<% if is_logged_in? %>
  <h3>Answer It!</h1>
  <form action="<%= answers_url %>" method="post">
    <input type="hidden" name="_method" value="post">
    <%= autho_token %>
    <input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
    <label for="body">body</label>
    <textarea name="answer[body]" id="body"></textarea>
    <input type="submit" name="submit" value="Answer">
  </form>
<% end %>