config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:create, :new, :destroy]

  resources :questions
  resources :answers, only: [:destroy, :edit, :update, :create]

  resources :tags, only: [:destroy, :edit, :update, :create, :index, :show] do
    resource :favorite, only: [:create, :destroy]
  end
  resources :taggables, only: [:create, :destroy]
  resource :favorite, only: [:show]

  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :votes, only: [:create]
  delete "votes", to: "votes#destroy"
  post "vote", to: "votes#upvote"
  delete "vote", to: "votes#downvote"

# Backbone App
  namespace :api do
    resource :session, only: [:create, :destroy] do
      get "current", to: "sessions#current"
    end
    get "notifications/:id", to: "notifications#read"
    get "notifications", to: "notifications#index"
    get "users/search/", to: "users#search"
    resources :users, only: [:create, :destroy, :index, :show, :update]
    get "questions/unanswered", to: "questions#unanswered"
    get "questions/noanswers", to: "questions#no_answers"
    resources :questions, only: [:create, :show, :index, :update, :destroy]
    post "questions/:id/best", to: "questions#best_answer"
    resources :answers, only: [:create, :destroy, :update, :show]
    resources :comments, only: [:create, :destroy, :update]

    post "tags/search/", to: "tags#search_chat"
    get "tags/search/", to: "tags#search"
    resources :tags, only: [:destroy, :edit, :update, :create, :index, :show] do
      resource :favorite, only: [:create, :destroy]
    end
    resources :taggables, only: [:create]
    delete "taggables", to: "taggables#destroy"
    get "favorites", to: "favorites#show"
    post "vote", to: "votes#upvote"
    delete "vote", to: "votes#downvote"
    post "chats/", to: "chats#set_main_chat"
    post "chats/:name/", to: "chats#set_chat_channel"
    get "chats/:name/", to: "chats#get_history"
    post "search/", to: "searches#search"
  end

# Switch between rails and backbone here
  root to: "apps#index"
# root to: "questions#index"
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:name, :description]
  pg_search_scope :search_by_name, :against => :name, :using =>{
                    :tsearch => {:prefix => true}
                  }
  paginates_per 12

  validates :name, presence: true, uniqueness: true, length: { minimum: 1 }

  has_many :taggables
  has_many :questions,
    through: :taggables,
    source: :taggings,
    source_type: "Question"
  has_many :favorites, inverse_of: :tag
  has_many :chats, inverse_of: :tag

end

app/controllers/api/tags_controller.rb
class Api::TagsController < Api::ApplicationController
  before_action :require_login, only: [:create, :edit, :update, :destroy]

  def index
    #@tags = Tag.all
    current_page = params[:page] || 1
    @tags = Tag.page(current_page)
    @total_pages = @tags.total_pages
    render template: "api/tags"
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      render template: "api/tag"
    else
      render json: "{ 'error': '#{@tag.errors.full_messages}'}",
      status: :unprocessable_entity
    end
  end
  def show
    # @tag = Tag.includes(:questions, questions: :user).find(params[:id])

    @tag = Tag.find(params[:id])
    if is_logged_in? && @tag
      @favorite = Favorite.find_by(
          user: current_user,
          tag: @tag
      )
    end
    if @tag
      render template: "api/tag"
    else
      render json: "{ 'error': 'That tag does not exist'",
      status: :not_found
    end
  end

  def search_chat
    @tags = Tag.search_by_name(params[:query]).limit(6)
    if @tags
       render template: "api/tags"
    else
      render text: "no result"
    end
  end

  def search
    current_page = params[:page] || 1
    @tags = Tag.search_by_name(params[:query]).page(current_page)
    if @tags
       render template: "api/tags"
    else
      render text: "no result"
    end
  end


  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      render template: "api/tag"
    else
      render json: "{ 'error': '#{@tag.errors.full_messages}'}",
      status: :unprocessable_entity
    end
  end

  private
  def tag_params
    params.require(:tag).permit(:name, :description)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_login, only: [:create, :edit, :update, :destroy]

  def index
    @tags = Tag.all
    render :index
  end

  def show
    # @tag = Tag.includes(:questions, questions: :user).find(params[:id])
    @tag = Tag.find(params[:id])
    render :show
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to tag_url(@tag)
    else
      flash[:msg] = @tag.errors.full_messages
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
    render :edit
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to tag_url(@tag)
    else
      flash[:msg] = @tag.errors_full_messages
      redirect_to tag_url(@tag)
    end
  end

  def destroy
    @quesiton = Tag.find(params[:id])
    if @quesiton.destroy
      redirect_to tags_url
    else
      flash[:msg] = @tag.errors_full_messages
      redirect_to tag_url(@tag)
    end
  end

  private
  def tag_params
    params.require(:tag).permit(:name, :description)
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>
<form action="<%= tag_url(@tag) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= autho_token %>
  <label for="name">Name</label>
  <input type="text" name="tag[name]" value="<%= @tag.name %>">
  <label for="description">description</label>
  <textarea name="tag[description]" id="description"><%= @tag.description %></textarea>
  <input type="submit" name="submit" value="Update Tag">
</form>

app/views/tags/index.html.erb
<h1>Tag All The Things!</h1>
<ul>
<% @tags.each do |tag| %>
  <% if is_logged_in? %>
    <li><a href="<%= tag_url(tag) %>"><%=h tag.name %></a></li>
    <form action="<%= tag_url(tag) %>" method="post">
      <%= autho_token %>
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="delete tag">
    </form>
  <% end %>
<% end %>

</ul>

app/views/tags/show.html.erb
<h1>Tag: <%=h @tag.name %></h1>
<% if is_logged_in? && !current_user.favorite_tags.include?(@tag) %>
  <form action="<%= tag_favorite_url(@tag) %>" method="post">
    <%= autho_token %>
    <input type="submit" value="add favoite">
  </form>
<% elsif is_logged_in? %>
  <form action="<%= tag_favorite_url(@tag) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= autho_token %>
    <input type="submit" value="remove favorite">
  </form>
<% end %>
<p>
  <%=h @tag.description %>
</p>
<% if is_logged_in? %>
  <a href="<%= edit_tag_url(@tag) %>">edit tag</a>
  <a href="<%= tags_url %>">see all tags</a>
<% end %>

<h2>Questions for <%=h @tag.name %></h2>

<% @tag.questions.each do |question| %>
<p>
  <strong>
    <a href="<%= question_url(question) %>"><%= question.title %></a>
  </strong>
  <%= question.body %>
</p>
<% end %>