config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:create, :new, :destroy]

  resources :questions
  resources :answers, only: [:destroy, :edit, :update, :create]

  resources :tags, only: [:destroy, :edit, :update, :create, :index, :show] do
    resource :favorite, only: [:create, :destroy]
  end
  resources :taggables, only: [:create, :destroy]
  resource :favorite, only: [:show]

  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :votes, only: [:create]
  delete "votes", to: "votes#destroy"
  post "vote", to: "votes#upvote"
  delete "vote", to: "votes#downvote"

# Backbone App
  namespace :api do
    resource :session, only: [:create, :destroy] do
      get "current", to: "sessions#current"
    end
    get "notifications/:id", to: "notifications#read"
    get "notifications", to: "notifications#index"
    get "users/search/", to: "users#search"
    resources :users, only: [:create, :destroy, :index, :show, :update]
    get "questions/unanswered", to: "questions#unanswered"
    get "questions/noanswers", to: "questions#no_answers"
    resources :questions, only: [:create, :show, :index, :update, :destroy]
    post "questions/:id/best", to: "questions#best_answer"
    resources :answers, only: [:create, :destroy, :update, :show]
    resources :comments, only: [:create, :destroy, :update]

    post "tags/search/", to: "tags#search_chat"
    get "tags/search/", to: "tags#search"
    resources :tags, only: [:destroy, :edit, :update, :create, :index, :show] do
      resource :favorite, only: [:create, :destroy]
    end
    resources :taggables, only: [:create]
    delete "taggables", to: "taggables#destroy"
    get "favorites", to: "favorites#show"
    post "vote", to: "votes#upvote"
    delete "vote", to: "votes#downvote"
    post "chats/", to: "chats#set_main_chat"
    post "chats/:name/", to: "chats#set_chat_channel"
    get "chats/:name/", to: "chats#get_history"
    post "search/", to: "searches#search"
  end

# Switch between rails and backbone here
  root to: "apps#index"
# root to: "questions#index"
end

app/views/layouts/_flash.html.erb
<% if flash[:msg] %>
  <div id="flash">
    <% if flash[:msg].is_a?(Array) %>
      <% flash[:msg].each do |msg| %>
        <p>
          <%= msg %>
        </p>
      <% end %>
    <% else %>
      <p>
        <%= flash[:msg] %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav>
  <div id="nav">
    <a href="<%= root_url %>">Qutria Home</a>
    <% if is_logged_in? %>
      <span> Hello <a href="<%= user_url(current_user) %>">
                  <%= current_user.username %></a> ! </span>
      <form id="log_out" action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <%= autho_token %>
        <input type="submit" name="delete" value="logout">
      </form>
    <% else %>
      <span>Hi There! </span> <a href="<%= new_user_url %>">Sign Up</a>
      <span> Or </span> <a href="<%= new_session_url %>">Log In</a>
    <% end %>
  </div>
</nav>

app/views/layouts/_user_form.html.erb
<% button_text = user.persisted? ? "Update User" : "Create user"  %>
<% action = user.persisted? ? user_url(user) : users_url   %>
<% method = user.persisted? ?  "PATCH" : "POST" %>
<form action="<%= action %>" method="post">
  <%= autho_token %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label for="username">Username</label>
  <input type="text" id="username" name="user[username]" value="<%= user.username %>">
  <label for="email">Email</label>
  <input type="text" id="email" name="user[email]" value="<%= user.email %>">
  <label for="password">password</label>
  <input type="password" id="password" name="user[password]" value="">
  <input type="submit" name="submit" value="<%= button_text %>">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/backbone.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qutria</title>
  <%= favicon_link_tag 'favicon.ico' %>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= filepicker_js_include_tag %>
  <script src="//js.pusher.com/2.2/pusher.min.js" type="text/javascript"></script>

  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.3/highlight.min.js"></script>
</head>
<body class="">
<script>
$( function () {
  Qutria.chat = new Pusher("<%= ENV['PUSHER_KEY'] %>");
  filepicker.setKey("<%= ENV['FILEPICKER'] %>");
});
</script>
<%= yield %>
</body>
</html>